# permissions for end users to view buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucket-viewer-role
rules:
- apiGroups:
  - bm.bmutziu.me
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bm.bmutziu.me
  resources:
  - buckets/status
  verbs:
  - get
